### ISSUE TITLE
audio source?

### ISSUE THREAD

**Issue by JOJ0** [hidimpu/Spotify-Downloader#2]
Hi, just a quick question without having to read you code: where does this get the audio actually from? most spotify downloaders somehow use the spotify api and then get tha actual audio from youtube. is your project working similar?
thanks in advance
best Jojo

**Comment by hidimpu** [comment]
I'm not using any specific Spotify Api here
Just a little help from web scraping to get the song and artist names.
Also, when an artist publishes their song ( with/without label), it gets distributed to all major platforms such as Spotify, Amazon music etc. 
Since YT Music is also present there, which is dependent on YT, it was quite good idea for me to use the Youtube_dl for this. 
Also it fetches 320kbps directly so no compromises with audio quality :)
