### ISSUE TITLE
THIS IS NOT A SPOTIFY DOWNLOADER

### ISSUE THREAD

**Issue by BrixSat** [hidimpu/Spotify-Downloader#4]
This is a great project but you dont download any song from spotify, instead you use youtube. Stop this fake app.

**Comment by hidimpu** [comment]
I respect your opinion about the same
The truth is, this app routes the query of the user through Spotify and fetches the details from that
Once the necessary details are fetched, then it processes it through YouTube and gets the file.
But as a user's perspective, it does what the user wants i.e. getting the song they want after putting the link so its ultimately that.
And personally I think, calling this app as "fake" is non appropriate because as a developer, I get to practice my skills on scraping and some more about python when I was learning new things.
